pass custom email parameters
HandCash/handcash-connect-sdk-js pull request #75
Opened 2023-09-29 14:43 UTC by brandonbryant12

2023-09-29 14:46 UTC, rafa-js requested changes
👍

2023-09-29 14:46 UTC, rafa-js commented on src/handcash_connect.ts
>  	 * @returns {string} requestId - The request id.
Update the JSDoc for consistency 🙏

2023-10-04 14:00 UTC, brandonbryant12 commented
updated

2023-10-04 14:03 UTC, rafa-js approved these changes
👍👍

2023-10-04 14:03 UTC, merged